### ISSUE TITLE
Log files not being written

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-notification-service#5]
In production log files do not appear to be output
e.g. nothing in local dir or /var/log/nodejs (expecting cognicity-notification-service.log)

**Comment by matthewberryman** [comment]
@abrahamq

**Comment by matthewberryman** [comment]
Sorry had forgotten about this- fairly low priority. Will take a quick look tomorrow.

**Comment by matthewberryman** [comment]
Not a bug; what's going on is that in our prod deployment the .env file had `LOG_LEVEL=debug` but our initial log messages e.g. https://github.com/urbanriskmap/cognicity-notification-service/blob/master/app.js#L56 are at info level so weren't captured (I've now bumped `LOG_LEVEL=info` on petabencana prod and I see the log file and log messages). @abrahamq

**Comment by matthewberryman** [comment]
^^ Edited previous comment if you're picking up this thread on email.
